---
- name: Uninstall Apache on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Remove Apache2 package
      apt:
        name: apache2
        state: absent
        purge: yes   # removes config files too

    - name: Remove unused dependencies
      apt:
        autoremove: yes
        purge: yes

